### ISSUE TITLE
onSelectedFilePaths() returning deselected file paths

### ISSUE THREAD

**Issue by ratanlp** [Angads25/android-filepicker#48] opened 2017-04-20 08:55 UTC
I have a requirement where user can select/deselect dirs paths. So after using dialog.markFiles(filePaths), and when the user is deselecting the path, still the onSelectedFilePaths() method returns deselected file paths along with selected paths.

**Comment by singhangadin** [comment] 2017-04-25 19:19
Are you sure that all the file paths that were pre-marked using `dialog.markFiles(filePaths)` were deselected? Please verify it again.

**Comment by ratanlp** [comment] 2017-04-29 16:43
The file paths that are marked are selected. The issue is when trying to deselect already marked ones.

**Comment by singhangadin** [comment] 2017-05-10 17:57
Hi, Apologies for getting back too late!. I think I have found the cause for this issue. The problem is that there can be multiple ways to define path of a directory, for eg.: `/mnt/sdcard/.VOD/100.png` and `/sdcard/.VOD/100.png` both of these paths are valid and correct for a file. However the path strings are different. This is due to internal directory structure of android which emulates /mnt/sdcard as /sdcard in its directory structure ([See here](http://stackoverflow.com/questions/12564884/is-there-a-difference-between-mnt-sdcard-and-sdcard)). As a solution to this, I will suggest you to use same path structure for files as of used in library (I am using [absolute path](https://github.com/Angads25/android-filepicker/blob/master/filepicker/src/main/java/com/github/angads25/filepicker/view/FilePickerDialog.java#L226) for linking files). This will help in pin pointing your marked files in library's list. Apart from that, thanks to you for informing, I thoroughly studied the method, and have found a bug in [markFiles](https://github.com/Angads25/android-filepicker/blob/master/filepicker/src/main/java/com/github/angads25/filepicker/view/FilePickerDialog.java#L316) method (which was marking all files as directory) which has been fixed by now.

**Closed as completed** 2017-05-10 18:07 UTC
